### ISSUE TITLE
[Map] The windows barricades placed by BuildingEd not working

### ISSUE THREAD

**Issue by SylvainMarty** [JulienLaclaverie/PZ_DieTonightMap#1]
The barricades placed on an empty windows don't working : we can pass through them !

@JulienLaclaverie says that it's because there isn't real "window", it's just an opening.

**Comment by JulienLaclaverie** [comment]
Also, the windows frames are not "baricadable"

**Comment by JulienLaclaverie** [comment]
Well, I tryed to place broken windows ont the window layer and saved it, the bug remains
