### ISSUE TITLE
[Mod] The gates animation don't match the timed animation duration

### ISSUE THREAD

**Issue by SylvainMarty** [JulienLaclaverie/PZ_DieTonightMap#11]
The gates animation are to quick and they don't match the timed animation duration.

**Comment by JulienLaclaverie** [comment]
Gates once open does'nt close properly
![image](https://cloud.githubusercontent.com/assets/9333772/26032660/f3e011c4-3898-11e7-9316-cdbc9e7f0a44.png)

**Comment by SylvainMarty** [comment]
I tried to find the more accurate way to match the timed action duration. Post a new comment here if the issue shows up again.
