### ISSUE TITLE
[Map] Some objects added with TileZed and BuildingEd not acting like normal objects

### ISSUE THREAD

**Issue by SylvainMarty** [JulienLaclaverie/PZ_DieTonightMap#2]
Example of objects which are not working : 
- Generators
- Barricades
- Light at the top of the watch tower

**Comment by JulienLaclaverie** [comment]
Also :
- Tents
- Campfires

**Comment by JulienLaclaverie** [comment]
According to the community, all these items are can't be created from the map edditor because they are just considered as images of done this way.

Our only solution might be to create all these items from a .lua mod file, which is really painfull, but I'll try to work on a solution...

**Comment by SylvainMarty** [comment]
We could make a lua script which replace the non-working sprites by working items. The script will be triggered only when starting a new game on the map. What do you think ?

**Comment by JulienLaclaverie** [comment]
Yes, that's what I thought, and that's what I did. I havn't commited it yet because of some issues remaining...

Though this problemes seems to be related to an other issue about the window frames not baricadable :/

**Comment by JulienLaclaverie** [comment]
But still, we are talking about calling something like 200~ calls to place objects just for the city, and those events cause stacktrace errors if the square is not loaded (seen / close to the player)

**Comment by SylvainMarty** [comment]
Arf yeah I see the difficulties with this solution... :/

**Comment by JulienLaclaverie** [comment]
I'm currently using Events.LoadGridsquare.Add and tiles placeholders to solve the issue

**Comment by JulienLaclaverie** [comment]
Should be solved now for windows and custom objects (campfires, compost, ...)

**Comment by JulienLaclaverie** [comment]
Should be fixed for now
