### ISSUE TITLE
The sound that triggers the zombie movement needs to be reworked

### ISSUE THREAD

**Issue by JulienLaclaverie** [JulienLaclaverie/PZ_DieTonightMap#21]
I think th sound is too "low" as it is now, it would be good if it were more from inside the city so that the zombies might go further inside it

**Comment by SylvainMarty** [comment]
We need to check the render in the distant server but it works great in self-hosted and single player.

There are now 3 sound points when the Horde spawn : 
![Scheme used to make the sound spatialisation](https://cloud.githubusercontent.com/assets/10723351/26522039/fdc0e876-42f7-11e7-8bd2-3e4aa5765fcc.png)

More zombies are now hanging inside the town.

**Comment by JulienLaclaverie** [comment]
well donne zone this zone !
