### ISSUE TITLE
Create a shader to make the game feels more like inside a desert

### ISSUE THREAD

**Issue by JulienLaclaverie** [JulienLaclaverie/PZ_DieTonightMap#23]
This needs to be tested on multiplayer too

**Comment by JulienLaclaverie** [comment]
Usefull tools to remove clothes : 
```
	pl:setClothingItem_Feet(nil)
	pl:setClothingItem_Legs(nil)
	pl:setClothingItem_Torso(nil)
```

**Comment by JulienLaclaverie** [comment]
To change the color of an item :
```
item:setColor( Color.new(r, g, b,1) );
```

**Comment by JulienLaclaverie** [comment]
![image](https://cloud.githubusercontent.com/assets/9333772/26367449/e8691d2e-3fee-11e7-98c4-d993b150b6e8.png)

**Comment by JulienLaclaverie** [comment]
Shaders looks good

**Comment by SylvainMarty** [comment]
Nice move ! Looks great !

**Comment by JulienLaclaverie** [comment]
Clothing are too much nested, Shaders do the work
