### ISSUE TITLE
Desert facities needs to have a Zombie spawn on load

### ISSUE THREAD

**Issue by JulienLaclaverie** [JulienLaclaverie/PZ_DieTonightMap#31]
We need to use placeholders (like for the campfires) and remove them on square load to spawn zombies at facilites in precise places.

- [ ]  Placeholder for 1 Zombie : 
- [ ]  Placeholder for 5 Zombie : 
- [ ]  Placeholder for 10 Zombie : 
- [ ]  Placeholder for 20 Zombie :

**Comment by SylvainMarty** [comment]
I put here the legend for all the placeholders we are using in the map tool to spawn things by the mod : 
<img width="523" alt="pz_dietonight_mod_map_placeholders_legend" src="https://user-images.githubusercontent.com/10723351/27122444-fb1fa58e-50ea-11e7-82d1-4eafb5afcad2.png">

**Comment by JulienLaclaverie** [comment]
You should integrate your code to the city objects code to avoid multiple code that check the square, this would end up being a performance problem.

Though this would mean renaming city objects too.

**Comment by SylvainMarty** [comment]
This was tested on single and multiplayer and it's working ! Now, we only need to use the placeholders :-)
