### ISSUE TITLE
The door mecanism needs to randomly breakdown after a few usage 

### ISSUE THREAD

**Issue by JulienLaclaverie** [JulienLaclaverie/PZ_DieTonightMap#40]
After X use, the door mecanism should randomly break and need electronicc scraps (and maybe 1 level in electronics) to be repaired

**Comment by SylvainMarty** [comment]
Good idea ! That would up the importance of the technician

**Comment by SylvainMarty** [comment]
Here are the features added from the last commit : 
- The door mechanism is now breakable : between 10 and 25 toggle before the mechanism break down
- Adding a repair option to the context menu which require to the player having at least 1 level in electricity, 5 electric wires, 5 eletronic scraps and a screwdriver in his inventory
- A technician can see the real condition of a gate terminal with a tooltip on the *Toggle door* option
- The reparation restore only the half of the full terminal life plus 5 HP by electricity level
